### ISSUE TITLE
android 7.x 打不开文章

### ISSUE THREAD

**Issue by zhirong2016** [25juan/CNode#1]
一直处于加载中

![qq 20180201180006](https://user-images.githubusercontent.com/18457728/35672536-d81834fc-0779-11e8-9fc3-5f7f49683f65.jpg)

**Comment by zhirong2016** [comment]
![image](https://user-images.githubusercontent.com/18457728/35673599-08179410-077d-11e8-8fd0-704ad4e38bf8.png)
看了代码  baseUrl那边是有一个空格的字符串   然后就一直卡加载中

**Comment by 25juan** [comment]
@zhirong2016  已经解决了
